[dnf]
repos = [
  "copr.fedorainfracloud.org/dejan/lazygit",
  "copr.fedorainfracloud.org/atim/starship",
  "copr.fedorainfracloud.org/scottames/ghostty",
]
packages = [
  # CLI tools
  "age",
  "bat",
  "eza",
  "fastfetch",
  "fd-find",
  "fish",
  "fzf",
  "gh",
  "ghostty",
  "git-delta",
  "htop",
  "jq",
  "lazygit",
  "nodejs",
  "pnpm",
  "ripgrep",
  "starship",
  "stow",
  "tealdeer",
  "tree",
  "zoxide",
]

[pnpm]
packages = [
  "opencode-ai",
]

[flatpak]
repos = [
  { name = "user:flathub", options = { url = "https://dl.flathub.org/repo/" } },
]
packages = [
  # Apps
  { name = "user:com.visualstudio.code", options = { remote = "flathub" } },
  { name = "user:app.zen_browser.zen", options = { remote = "flathub" } },
  { name = "user:org.mozilla.firefox", options = { remote = "flathub" } },
  { name = "user:com.jetbrains.WebStorm", options = { remote = "flathub" } },
  { name = "user:com.spotify.Client", options = { remote = "flathub" } },
  { name = "user:com.valvesoftware.Steam", options = { remote = "flathub" } },
  { name = "user:com.discordapp.Discord", options = { remote = "flathub" } },
  { name = "user:org.videolan.VLC", options = { remote = "flathub" } },
  { name = "user:com.obsproject.Studio", options = { remote = "flathub" } },
  { name = "user:md.obsidian.Obsidian", options = { remote = "flathub" } },
]
