[brew]
packages = [
  "steam",
  "discord",
  "obs",
]

[dnf]
packages = [
  "steam",
  "steam-devices",
]

[flatpak]
packages = [
  { name = "user:com.discordapp.Discord", options = { remote = "flathub" } },
  { name = "user:com.obsproject.Studio", options = { remote = "flathub" } },
]
