hostname_groups_enabled = true

[hostname_enabled_backends]
Zachs-MacBook-Pro = ["brew"]
VUMACBOOK = ["brew"]
fedora = ["dnf", "flatpak"]

[hostname_groups]
Zachs-MacBook-Pro = ["macbook", "home-macbook"]
VUMACBOOK = ["macbook", "work-macbook"]
fedora = ["fedora-base", "fedora-home"]
